#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/../config/boot'
require RAILS_ROOT + '/config/environment'

etFolder = ExhibitType.find_by_key("folder")
etJPG = ExhibitType.find_by_key("jpg")


eHome = Exhibit.new()
eHome.title = "Home"
eHome.exhibit_type_id = etFolder.id
eHome.save!
puts "The new library is open - ##{eHome.id}"


eTrucks = Exhibit.new(:title => "Get your trucks here!")
eTrucks.upload_file_from_filesystem("./demo/images/trucks.jpg")
eTrucks.save!



eBookLibrary = ExhibitLink.new()
eBookLibrary.exhibit_id = eHome.id
eBookLibrary.inner_exhibit_id = eTrucks.id
eBookLibrary.save!
